### ISSUE TITLE
[Hackweek 23] Add support for Zorin OS 16.3 Education

### ISSUE THREAD

**Issue by deneb-alpha** [uyuni-project/uyuni#7839]
# Description
This is part of the Hackweek 23 project [Testing and adding GNU/Linux distributions on Uyuni](https://hackweek.opensuse.org/23/projects/testing-gnu-slash-linux-distributions-on-uyuni).

Zorin OS
In particular the Education version (https://help.zorin.com/docs/getting-started/system-requirements/ and https://zorin.com/os/education/)

Note: Because of the ID_LIKE and the UBUNTU_CODENAME values, it should be compatible with the bundle and client tools for Ubuntu 20.04 out of the box.

This is a distro **based on Ubuntu 20.04**. 
This is the content of **/etc/os-release**: 
~~~
NAME="Zorin OS" VERSION="16.3" 
ID=zorin 
ID_LIKE=ubuntu 
PRETTY_NAME="Zorin OS 16.3" 
VERSION_ID="16" 
HOME_URL="https://zorin.com/os/" 
SUPPORT_URL="https://help.zorin.com/" 
BUGREPORTURL="https://zorin.com/os/feedback/" 
PRIVACYPOLICYURL="https://zorin.com/legal/privacy/" 
VERSION_CODENAME=focal 
UBUNTU_CODENAME=focal
~~~

# Tasks
- [ ] Reposync (this will require using spacewalk-common-channels and adding channels to the .ini file)
- [ ] Onboarding (both salt and salt-ssh) (this will probably require adding OS to the bootstrap repository creator)
- [ ] Package management (install, remove, update...)
- [ ] Patching (if patch information is available, could require writing some code to parse it, but IIRC we have support for Ubuntu already)
- [ ] Applying any basic salt state (including a formula)
- [ ] Salt remote commands
- [ ] Bonus point: Java part for product identification, and monitoring enablement
- [ ] Bonus point: sumaform enablement (https://github.com/uyuni-project/sumaform)
- [ ] Bonus point: Documentation (https://github.com/uyuni-project/uyuni-docs)
- [ ] Bonus point: testsuite enablement (https://github.com/uyuni-project/uyuni/tree/master/testsuite)
