### ISSUE TITLE
Fix Cucumber feature `min_salt_install_package` which is only testing patch installation

### ISSUE THREAD

**Issue by meaksh** [uyuni-project/uyuni#7980]
Issue created by automation script. Original author: @Bischoff Date: 2023-08-16T12:34:27Z
Source issue: https://github.com/SUSE/spacewalk/issues/22327

---
### Context

The file `testsuite/features/secondary/min_salt_install_package.feature` starts with:
```
Feature: Install a patch on the client via Salt through the UI
````
and indeed it tests patching, but the title and the action of this feature doesn't match.
So we in fact want to test both package and patch installation.

Background information:

We do package install tests on the Salt minion in:
```
min_bootstrap_script.feature,
min_salt_install_with_staging.feature,
min_salt_pkgset_beacon.feature , and
min_salt_software_states.feature
```
but it's in quite specific setups.

We already have features with `install_package_and_patch` in the name:
```
min_rhlike_salt_install_package_and_patch.feature 
trad_inst_package_and_patch.feature
```

We also have features with `install_package` only in the name:
```
minssh_salt_install_package.feature
```

According to the logs, the issue traces back to 2018. I was not able to dig earlier.

### Tasks

- [x] Rename to `min_salt_install_package_and_patch.feature`
- [x] Add a package install test in `min_salt_install_package_and_patch.feature`

Additionally, to have homogeneity on these Cucumber features we will refactor the minssh client test.

- [x] Rename `minssh_salt_install_package.feature` to `minssh_salt_install_package_and_patch.feature`
- [x] Add a patch install test in `minssh_salt_install_package_and_patch.feature`

**Comment by meaksh** [comment]
Comment created by automation script. Original author: @srbarrios. Date: 2023-08-21T10:00:29Z

---
I like option 2. BUT,

I would also refactor `minssh_salt_install_package.feature` to become `minssh_salt_install_package_and_patch.feature` that would bring some sense of homogeneity for these features on regard to clients tested.

**Comment by meaksh** [comment]
Comment created by automation script. Original author: @srbarrios. Date: 2023-08-21T10:38:35Z

---
This card was edited, before we had these three solutions:

> **Solution 1**: rename to min_salt_install_patch.feature
> **Solution 2**: rename to min_salt_install_package_and_patch.feature, and add a package install test
> **Solution 3**: rename to min_salt_install_patch.feature, and create a new min_salt_install_package.feature
